# -*- coding: utf-8 -*-
"""Covid_EUA_Traking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_ofDLq8ULvIHSJ6OYlE5kQXSaT3jmmW
"""

# ================================================
# 🧠 PASSO 1 - Escolher uma base de dados pública
# ================================================
# Base escolhida: bigquery-public-data.covid19_tracking.city_level_cases_and_deaths
# Tema: Casos e mortes por COVID-19 em cidades dos EUA
# Fonte: Google Cloud Public Datasets
# ================================================


# ================================================
# ⚙️ PASSO 2 – Configurar o ambiente Python
# ================================================

!pip install pandas-gbq --quiet
!pip install seaborn matplotlib --quiet

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas_gbq import read_gbq

# Configurações visuais
plt.style.use("seaborn-v0_8-whitegrid")
pd.set_option("display.max_columns", 20)

# ================================================
# 📊 PASSO 3 – Extrair os dados via SQL
# ================================================
query = """
    SELECT
      date,
      state,
      location AS city,
      cases_total,
      daily_new_cases,
      deaths_total,
      daily_new_deaths
    FROM `bigquery-public-data.covid19_tracking.city_level_cases_and_deaths`
    WHERE city_or_county = 'City'
      AND cases_total IS NOT NULL
    ORDER BY date DESC
    LIMIT 5000
"""

# Replace 'your-gcp-project-id' with your actual Google Cloud project ID and specify a location
df = read_gbq(query, project_id="curso-ebac1", dialect='standard')
print("✅ Dados importados com sucesso!\n")
df.head()

# ================================================
# 🧹 PASSO 4 – Tratamento e exploração dos dados
# ================================================

# Verificar dados ausentes
print("🔍 Dados ausentes por coluna:")
print(df.isnull().sum(), "\n")

# Converter a coluna de data
df["date"] = pd.to_datetime(df["date"])

# Estatísticas descritivas
print("📈 Estatísticas descritivas:")
print(df.describe(), "\n")

# Informações gerais
df.info()

# Ver as cidades mais recorrentes no dataset
print("\n🏙️ Top 10 cidades com mais registros:")
print(df["city"].value_counts().head(10))

# ================================================
# 💡 PASSO 5 – Definir perguntas de negócio
# ================================================
# 1️⃣ Quais são as cidades com maior número total de casos acumulados?
# 2️⃣ Como evoluíram os casos diários ao longo do tempo nas cidades mais afetadas?
# 3️⃣ Qual a relação entre casos e mortes diárias?

# ================================================
# 📊 PASSO 6 – Responder as perguntas com código
# ================================================

# 1️⃣ Cidades com maior número total de casos acumulados
top_cities = (
    df.groupby("city")["cases_total"]
    .max()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)
print("🏆 Top 10 cidades com mais casos acumulados:")
print(top_cities)

plt.figure(figsize=(10, 5))
sns.barplot(x="cases_total", y="city", data=top_cities, palette="Reds_r")
plt.title("Top 10 Cidades com Mais Casos de COVID-19")
plt.xlabel("Casos Totais")
plt.ylabel("Cidade")
plt.show()

# 2️⃣ Evolução temporal dos casos diários
plt.figure(figsize=(12, 6))
sns.lineplot(data=df[df["city"].isin(top_cities["city"])],
             x="date", y="daily_new_cases", hue="city", linewidth=1.5)
plt.title("Evolução dos Casos Diários nas Cidades Mais Afetadas")
plt.xlabel("Data")
plt.ylabel("Novos Casos Diários")
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

# 3️⃣ Relação entre casos e mortes diárias
plt.figure(figsize=(6, 6))
sns.scatterplot(data=df, x="daily_new_cases", y="daily_new_deaths", alpha=0.6)
plt.title("Correlação entre Casos e Mortes Diárias")
plt.xlabel("Novos Casos")
plt.ylabel("Novas Mortes")
plt.show()

# ================================================
# 🧾 PASSO 7 – Conclusão
# ================================================

print("""
📊 CONCLUSÕES PRINCIPAIS:

1️⃣ As cidades com maior número total de casos acumulados concentram boa parte do impacto da pandemia,
    destacando-se grandes centros urbanos.

2️⃣ Observa-se que os picos de novos casos variam entre as cidades, mas seguem tendências temporais
    semelhantes, indicando ondas regionais da pandemia.

3️⃣ Há uma correlação positiva entre novos casos e novas mortes diárias — indicando que o aumento
    no número de casos tende a ser seguido por maior número de óbitos.

💡 Essa análise demonstra o potencial do BigQuery aliado ao Python para realizar análises rápidas e
    escaláveis sobre dados públicos de alta volumetria.
""")